baseURL = 'https://plataformas-moviles.vercel.app'
languageCode = 'es-AR'
defaultContentLanguage = 'es'
title = 'Plataformas Móviles'
disableKinds = ['taxonomy', 'term']

[params]
	mainSections = ['clases']
	repository = 'https://github.com/tehuel/plataformas-moviles'

[frontmatter]
	date = [':filename', ':default']

[markup.goldmark.renderer]
	unsafe= true
