baseURL = 'https://plataformas-moviles.vercel.app'
languageCode = 'es-AR'
defaultContentLanguage = 'es'
title = 'Plataformas Móviles'
disableKinds = ['taxonomy', 'term']

[params]
	mainSections = ['clases']

[frontmatter]
	date = [':filename', ':default']

